# Generated by Django 4.2.6 on 2024-02-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_item_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('business', 'Business'), ('residential', 'Residential')], default='residential', max_length=20),
        ),
    ]
