# Generated by Django 4.2.6 on 2024-02-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_item_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='county',
            field=models.CharField(choices=[('Nako', 'Nako'), ('Mako', 'Mako')], max_length=50),
        ),
    ]
